name: letsrun
description: This application is the final project of our career as developers.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  nice_button: ^0.1.7
  avatar_glow: ^1.1.0
  firebase_core: ^0.4.4+3
  firebase_storage: ^3.1.5
  cloud_firestore: ^0.13.5
  firebase_auth: ^0.16.0
  image_picker: ^0.6.5+3
  curved_navigation_bar: ^0.3.2
  animated_card: ^1.0.0+8
  like_button: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/img/illustration.png
    - assets/img/shoe.png
    - assets/img/cam.png
    - assets/img/cam2.png

  fonts:
    - family: Bebas
      fonts:
        - asset: assets/fonts/bebas_regular.otf
        - asset: assets/fonts/bebas_bold.otf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins_regular.ttf
        - asset: assets/fonts/poppins_bold.ttf
          weight: 700
    - family: Lobster
      fonts:
        - asset: assets/fonts/lobster-regular.ttf
          weight: 700
